### ISSUE TITLE
Input doesn't focus when component is clicked on iOS Safari

### ISSUE THREAD

**Issue by danconnell** [cibernox/ember-power-select#602]
Using Safari on an iOS device, when you click the component and it opens, the search input isn't focused as part of the click event's thread.

This presents a problem because trying to focus the input in callbacks doesn't accomplish anything because Safari on iOS doesn't allow the keyboard to be opened except by actual user interaction.

Is there any way around this? Is this a bug?

**Comment by cibernox** [comment]
I wasn't aware of that limitation of iOS. I guess that it should be considered a bug.

Funny enough, I just merged a PR a couple days ago to allow users to achieve the behaviour you consider a bug 😁 https://github.com/cibernox/ember-power-select/issues/593#issuecomment-234481628

**Comment by cibernox** [comment]
I think that this might have been fixed already.

**Comment by Charizard** [comment]
@cibernox I can confirm that this is happening in iOS. The search box is not focused on clicking the dropdown.

**Comment by bmfay** [comment]
@cibernox I went to open a ticket for this very issue, but d found that there was already a closed ticket for this.  This was closed with "I think that this might have been fixed already" but it seems it never was fixed.  We are still seeing this issue.  I am using what I understand to be the latest stable version ("ember-power-select": "^1.10.4") as the README says 2.x is still in beta.  Would you have reason to believe this would be resolved by upgrading to the latest 2.X?  Thanks.

**Comment by cibernox** [comment]
@bmfay Sorry, that comment was outdated. 2.0 came out of beta a long time ago. Can you confirm if updating it fixes the problem?

**Comment by bmfay** [comment]
@cibernox that was a false positive actually, updating did not fix the problem.  The issue remains...
