### ISSUE TITLE
CP for tagName throws error on Ember 2.8.x

### ISSUE THREAD

**Issue by blimmer** [cibernox/ember-power-select#659]
@cibernox - the issue fixed in #557 now throws errors on 2.8.x. My project is currently on 0.10.x and it seems like all other releases are currently in beta (0.11.x and 1.0.x).

What is your recommendation? Is the beta stable enough to use in production? Should we backport the fix to the 0.10.x branch? My app uses LTS, so I'm usually a bit hesitant to be using betas in prod.

The error thrown is pretty cryptic and I only found that it was power-select by digging through the stack.
```
testem.js:962 Ember encountered an error. Error: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.
    at Error (native)
    at DOMHelper.prototype.createElement (http://localhost:3334/assets/vendor.js:14560:30)
    at Object.buildFragment (http://localhost:3334/assets/vendor.js:57681:23)
    at getCachedFragment (http://localhost:3334/assets/vendor.js:57914:29)
    at Function.RenderResult.build (http://localhost:3334/assets/vendor.js:57629:20)
    at render (http://localhost:3334/assets/vendor.js:57593:37)
    at http://localhost:3334/assets/vendor.js:58416:7
    at renderAndCleanup (http://localhost:3334/assets/vendor.js:58451:18)
    at Block._firstRender (http://localhost:3334/assets/vendor.js:58413:5)
    at Block.invoke (http://localhost:3334/assets/vendor.js:58391:12)
```

**Comment by KrisOlszewski** [comment]
Same here. Updated Ember to 2.8 and every route with power-select is broken. Tried upgrading to latest beta, but it doesn't seem to be compatible with 0.10.X settings.

**Comment by cibernox** [comment]
I'm on holidays but I think that updating to 1.0 should fix the issue. At
test builds were green in beta (now 2.8) when I left

**Comment by cemarte** [comment]
Hi @cibernox ,

I tried upgrading to 1.0.0-beta.14, it really solves the issue with tagName.

Thanks

**Comment by KrisOlszewski** [comment]
@cemarte same here, updated to latest beta, fixed CSS issues and it's working with Ember 2.8
 
@cibernox thanks for an awesome plugin!

**Comment by knownasilya** [comment]
I updated from beta.4 to beta.14 and still seeing the issue. Cleared my node modules and dist dir and still no change.

**Comment by knownasilya** [comment]
Had to update the version in another addon ..

**Comment by mupkoo** [comment]
@knownasilya which addon did you update. 
I get an error telling me that you cannot use `attributesBindings` on a tag-less component

**Comment by knownasilya** [comment]
@mupkoo ember-palette and ember-power-elect-sortable.

Your issue seems unrelated. Sounds more like an issue with using `id=...` on a `{{liquid-*}}` helper in liquid-fire.

**Comment by cibernox** [comment]
This seems to be fixed. Closing.
